version: "3"
services:
  api:
    image: laidbackak/jotter-api
    ports:
      - 80:8000
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: